package com.yixin.study.dao.common;

import java.io.Serializable;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yixin.study.model.example.GenericExample;


public interface GenericExampleMapper<T extends Serializable, PK extends Serializable, EX extends GenericExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vin_import_task
     *
     * @mbggenerated Thu Apr 02 17:59:22 CST 2015
     */
    int countByExample(EX example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vin_import_task
     *
     * @mbggenerated Thu Apr 02 17:59:22 CST 2015
     */
    int deleteByExample(EX example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vin_import_task
     *
     * @mbggenerated Thu Apr 02 17:59:22 CST 2015
     */
    int deleteByPrimaryKey(PK id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vin_import_task
     *
     * @mbggenerated Thu Apr 02 17:59:22 CST 2015
     */
    int insert(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vin_import_task
     *
     * @mbggenerated Thu Apr 02 17:59:22 CST 2015
     */
    int insertSelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vin_import_task
     *
     * @mbggenerated Thu Apr 02 17:59:22 CST 2015
     */
    List<T> selectByExample(EX example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vin_import_task
     *
     * @mbggenerated Thu Apr 02 17:59:22 CST 2015
     */
    T selectByPrimaryKey(PK id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vin_import_task
     *
     * @mbggenerated Thu Apr 02 17:59:22 CST 2015
     */
    int updateByExampleSelective(@Param("record") T record, @Param("example") EX example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vin_import_task
     *
     * @mbggenerated Thu Apr 02 17:59:22 CST 2015
     */
    int updateByExample(@Param("record") T record, @Param("example") EX example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vin_import_task
     *
     * @mbggenerated Thu Apr 02 17:59:22 CST 2015
     */
    int updateByPrimaryKeySelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vin_import_task
     *
     * @mbggenerated Thu Apr 02 17:59:22 CST 2015
     */
    int updateByPrimaryKey(T record);
}
